# Generated by Django 2.2.13 on 2020-06-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retention_data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_eop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_premajor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='system_key',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='uw_netid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
