# Generated by Django 2.2.13 on 2020-06-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retention_data_pipeline', '0002_auto_20200630_0231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('year', 'quarter', 'system_key')},
        ),
    ]
