# Generated by Django 2.2.13 on 2020-07-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retention_data_pipeline', '0003_auto_20200630_0234'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
