# Generated by Django 2.2.13 on 2020-07-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retention_data_pipeline', '0004_auto_20200701_0024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('year', 'quarter', 'system_key')},
        ),
    ]
